"""Freeze the current interpreter's environment into deploy pins.

Run this INSIDE the freshly-trained environment (``make freeze`` does that for
you) so the versions written to ``requirements.txt`` and ``.python-version``
exactly match the environment that produced ``models/*.pkl``. Matching versions
is what lets Streamlit Cloud unpickle the models without the
``InconsistentVersionWarning`` -> ``AttributeError`` crash.
"""

from __future__ import annotations

import sys
from importlib.metadata import version

# Top-level packages the app + training code actually import. scipy and
# threadpoolctl are scikit-learn's compiled dependencies; pinning them too keeps
# the cloud build byte-for-byte deterministic.
PACKAGES = [
    "joblib",
    "numpy",
    "pandas",
    "scikit-learn",
    "scipy",
    "streamlit",
    "threadpoolctl",
]


def main() -> None:
    """Freeze the fixed PACKAGES list to requirements.txt at installed versions and write .python-version."""
    lines = [
        "# Auto-generated by `make freeze` (scripts/pin_env.py).\n",
        "# Pinned to the exact environment that trained models/*.pkl.\n",
    ]
    lines += [f"{pkg}=={version(pkg)}\n" for pkg in PACKAGES]
    with open("requirements.txt", "w", encoding="utf-8", newline="\n") as f:
        f.writelines(lines)

    py = f"{sys.version_info.major}.{sys.version_info.minor}\n"
    with open(".python-version", "w", encoding="utf-8", newline="\n") as f:
        f.write(py)

    print("".join(lines), end="")
    print(f"# .python-version -> {py}", end="")


if __name__ == "__main__":
    main()
